- name: Instalando o nginx

  hosts: docker
  
  tasks:


   - name: stop apache2 debian
     service:
      name: apache2
      state: stopped
     when: ansible_os_family == "Debian"

   - name:: remove o apache2
     package:
      name: apache2
      state: absent

   - name: install nginx
     package:
      name: nginx
      state: present
      update_cache: yes
